name: NodeJS Scanner

on:
  workflow_call:
    secrets:
      TRIVY_SLACK_WEBHOOK: 
        required: true
        description: "Webhook for Security Team's Slack Channel to send alerts on failed scans"
        

jobs:
  nodejs_scan:
    permissions:
      contents: read
      actions: read
      
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.TRIVY_SLACK_WEBHOOK }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      NJS_PR_URL: ${{ github.event.pull_request.html_url }}
      NJS_PR_CREATOR: ${{ github.event.pull_request.user.login }}
      NJS_HEAD_COMMIT: ${{ github.event.pull_request.html_url }}/commits/${{ github.event.pull_request.head.sha }}
      NJS_WORKFLOW_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      NJS_SENDER: ${{ github.event.sender.login }}
      JOB_URL_NOT_FOUND: "*Job URL not found, Please Visit the Workflow URL to review failed checks...*"
      NJS_SCAN_FAILED: false
      NJS_SCAN_SUMMARY: "No Results Found"
      
    name: NodeJS Security Scan
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout code v4
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Install njsscan
        run: |
          pip3 install njsscan==0.3.7
          
      - name: NodeJS Scan - JSON Format
        run: |
          set +e
          njsscan . --config .njsscan-config.yml --json --output njsscan-result.json || true

      - name: Parse JSON Scan File
        run: |

          # We are using jq in docker because the functionality to 
          # dynamically select keys wasn't working with jq-1.6 
          # which is installed by default in github actions runner.
          
          SCAN_FILE="njsscan-result.json"
          scan_failed=false
          high_vuln_count=0
          medium_vuln_count=0
          info_vuln_count=0
          total_vuln_count=0
          
          function update_severity_count {
          
              context="$1"
              vuln_keys="$2"
              
              echo "-----Counting Vulnerabilities for $context Context-----"
          
              for vuln_key in $vuln_keys
              do
                  severity=$(cat $SCAN_FILE | docker run --rm -i ghcr.io/jqlang/jq:1.7.1 -r --arg context "$context" --arg vuln_key "$vuln_key" '.[$context].[$vuln_key].metadata.severity')
                  echo "Vuln Key: $vuln_key and Severity: $severity"
          
                  case $severity in
                      INFO)
                          info_vuln_count=$(( $info_vuln_count + 1 ))
                          ;;
                      
                      WARNING)
                          medium_vuln_count=$(( $medium_vuln_count + 1 ))
                          ;;
                      
                      ERROR)
                          high_vuln_count=$(( $high_vuln_count + 1 ))
                          ;;
                      
                      *)
                          echo "Unknown Severity: $severity for Vuln Key: $vuln_key"
                          ;;
                  esac
              done
          }
          
          nodejs_keys=$(cat $SCAN_FILE | docker run --rm -i ghcr.io/jqlang/jq:1.7.1 -r 'select(.nodejs) | .nodejs | keys[]')
          
          if [[ ! -z ${nodejs_keys} ]]; then
              update_severity_count "nodejs" "$nodejs_keys"
          fi
          
          templates_keys=$(cat $SCAN_FILE | docker run --rm -i ghcr.io/jqlang/jq:1.7.1 -r 'select(.templates) | .templates | keys[]')
          
          if [[ ! -z "$templates_keys" ]]; then
              update_severity_count "templates" "$templates_keys"
          fi
          
          total_vuln_count=$(( $high_vuln_count + $medium_vuln_count + $info_vuln_count ))
          
          scan_summary="\n *Total Vuln Count: $total_vuln_count*\n *Breakdown:*\n\t *High Vuln Count: $high_vuln_count*\n\t *Medium Vuln Count: $medium_vuln_count*\n\t *Info Vuln Count: $info_vuln_count*"

          
          if [[ "$total_vuln_count" -gt 0 ]]; then
              scan_failed=true
              echo "NJS_SCAN_FAILED=${scan_failed}" >> $GITHUB_ENV
              echo "Scan Summary:"
              echo -e "$scan_summary"
              echo "NJS_SCAN_SUMMARY=${scan_summary}" >> $GITHUB_ENV
          fi

      - name: NodeJS Scan - Table Format
        run: |
          set +e
          njsscan . --config .njsscan-config.yml > njsscan-result.out 2>&1
          cat njsscan-result.out | grep -vE -- "- Pattern Match|- Semantic Grep"

          if [[ "$NJS_SCAN_FAILED" == "true" ]]
          then
            exit 1
          fi
        
      - name: Extract Job URL
        if: ${{ always() && env.NJS_SCAN_FAILED == 'true' }}
        run: |
          job_id=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}/jobs | jq '.jobs[]? | select(.name=="nodejs_scanner / NodeJS Security Scan") | .id')
            
          if [[ ! -z ${job_id} && ${job_id} != "null" ]]; then
            job_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${job_id}"
            echo "NJS_JOB_URL=${job_url}" >> $GITHUB_ENV   
          fi
          
      # - name: Send custom JSON data to Slack workflow
      #   if: ${{ always() && env.NJS_SCAN_FAILED  == 'true' }}
      #   uses: slackapi/slack-github-action@6c661ce58804a1a20f6dc5fbee7f0381b469e001 # v1.25.0
      #   with:
      #     # For posting a rich message using Block Kit
      #     payload: |
      #       {
      #         "blocks": [
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": ":red-alert: *NodeJS Scan Failed*"
      #             }
      #           },
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": "`Workflow Run:` ${{ env.NJS_WORKFLOW_RUN_URL }}\n\n`JOB URL:` ${{ env.NJS_JOB_URL || env.JOB_URL_NOT_FOUND }}\n\n`Pull Request:` ${{ env.NJS_PR_URL }}\n\n`Head Commit:` ${{ env.NJS_HEAD_COMMIT }}\n\n`PR Creator:` *${{ env.NJS_PR_CREATOR }}*\n\n`Latest Committer:` *${{ env.NJS_SENDER }}*\n\n`Scan Summary:` ${{ env.NJS_SCAN_SUMMARY }}"
      #             }
      #           }
      #         ]
      #       }
          
